### ISSUE TITLE
Privacy setting on peer mentoring groups video 

### ISSUE THREAD

**Issue by glo-ria368** [ZumeProject/zume-training-system#288] opened 2024-04-18 10:23 UTC
In session 19, the peer mentoring groups video has a privacy setting on it

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/ae228d07055140e095b45b6031dc2827/screenshot/ec3f2284-ef06-4070-8ce9-b89b98f20a12.png)

-------------------------------------

**Website URL:**
[https://zume5.training/presenter?type=20&session=19&view=slideshow](https://zume5.training/presenter?type=20&session=19&view=slideshow)

**Device and browser info:**
Chrome 123.0.6312.58 (1440x754) | Mac OS (x86) 10.15.7

**Date and time:**
April 18th 2024 | 10:22am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/f47cb92b-f4a5-4f8b-8e09-fd683bc44bdd](https://jam.dev/c/f47cb92b-f4a5-4f8b-8e09-fd683bc44bdd)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment] 2024-04-18 13:30
duplicate of #184

**Closed by squigglybob** 2024-04-18 13:30 UTC
