### ISSUE TITLE
getting an privacy message on the video for the coaching checklist

### ISSUE THREAD

**Issue by glo-ria368** [ZumeProject/zume-training-system#285] opened 2024-04-18 10:15 UTC
In session 17. Can't see it here bc the screen changes when I try to screenshot it

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/35670b6fc3d82564d0a50d8745cccc90/screenshot/a11d65c0-ba0c-4a67-907d-0a3026ca9a37.png)

-------------------------------------

**Website URL:**
[https://zume5.training/presenter?type=20&session=17&view=slideshow](https://zume5.training/presenter?type=20&session=17&view=slideshow)

**Device and browser info:**
Chrome 123.0.6312.58 (1440x754) | Mac OS (x86) 10.15.7

**Date and time:**
April 18th 2024 | 10:15am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/75d6f174-d8eb-457d-b6c3-e324e799c068](https://jam.dev/c/75d6f174-d8eb-457d-b6c3-e324e799c068)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment] 2024-04-18 13:30
closing as this is a duplicate of #184 

All of the privacy issues with the videos are all due to the same thing. We will try and fix them all at once.

Once we have attempted a fix we will need to run through all videos to double check them

**Closed by squigglybob** 2024-04-18 13:30 UTC
